### ISSUE TITLE
Can not ping global IPv6 address from mesh network

### ISSUE THREAD

**Issue by artokin** [ARMmbed/mbed-access-point#1]
We are not able to ping global IPv6 addresses from a mesh network. 

Our system setup is as follows:
- a mbed 6LoWPAN Border Router HAT connected to mbed-access-point
- mbed-access-point (using pre-compiled binary) is connected to wireless router that provides IPv6 (/64) address
- mesh end node that is connected to mbed 6LoWPAN Border Router HAT via RF interface

When the system is up and running:
- Mesh end device is able to ping Raspberry Pi global address
- Raspberry Pi is able to ping global IPv6 address (like ipv6.google.com)

However, the mesh end device is not able to ping global address. The ping command enters Raspberry Pi but there is no response to the command.

**Comment by urutva** [comment]
In the previous releases, it was mandatory for the backbone router to support DHCP-PD for proper functioning of mbed access point. With the current release https://github.com/ARMmbed/mbed-access-point/releases/tag/mbedap-v3.0.0, the neighbor discovery proxy is supported for the mesh network when the mbed access point gets only /64 prefix on the WAN side. This fixes the ping issue observed when the backbone router doesn't support DHCP-PD.
