### ISSUE TITLE
Access required to private repos to build mbed-access-point

### ISSUE THREAD

**Issue by jzehler** [ARMmbed/mbed-access-point#4]
I'm trying to follow the build instructions for the mbed-access-point.  I need to do a custom build with Pi 3 support.  When I run prepare.sh, it prompts me for username/password for private repo https://github.com/ARMmbed/luci-private.git.  A colleague of mine also said later in the build process there is another private repo he needed access to for a custom version of odhcpd.  How can I get access to the private repos needed to manually build mbed-access-point?

**Comment by MarceloSalazar** [comment]
@devran01 please have a look to this (may need internal discussion).

**Comment by jzehler** [comment]
I just ran into the odhcpd issue my colleague mentioned to me.  Below is the output from the build related to this issue...

Checking out files from the git repository...
Cloning into 'odhcpd-2017-03-24'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by MarceloSalazar** [comment]
FYI we are looking into the changes to point at the upstream Luci (public) repo.

**Comment by urutva** [comment]
@jzehler The "odhcpd" module is public, but Makefile uses "git" protocol to clone the repository. The "git" protocol uses port 22 and SSH keys for authentication (https://help.github.com/articles/which-remote-url-should-i-use/).

**Comment by jzehler** [comment]
Closing this since I'm able to build mbed-access-point now.
