### ISSUE TITLE
mbed Border Router HAT not getting global ipv6 on backhaul or rf interfaces

### ISSUE THREAD

**Issue by jzehler** [ARMmbed/mbed-access-point#5]
I was able to successfully build nanostack-border-router and flash the bin to the HAT.  When I set the jumper back to “on”, plug it into my Pi3 and boot my Pi3…  it doesn’t seem to work.
 
The led on the mbed Border Router HAT flashes green continuously.  I don’t seem to be getting a global ipv6 on the backhaul interface or the rf interface on the mbed Border Router HAT…
 
[INFO][brro]: Backhaul interface addresses:
[INFO][brro]:  [0] fe80::3441:efff:fe1f:b139
[INFO][brro]: RF interface addresses:
[INFO][brro]:  [0] fe80::802c:75ce:9527:6c47
[INFO][brro]:  [1] fd00:db8::ad6f:53d4:6a4e:52de
[INFO][brro]:  [2] fd00:db8::ff:fe00:9400
[INFO][brro]:  [3] fd00:db8::ff:fe00:fc00
 
I also don’t seem to be getting a global ipv6 on the sl0 interface on the mbed-access-point…
 
eth0      Link encap:Ethernet  HWaddr B8:27:EB:13:A8:1A
          inet addr:192.168.1.122  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: 2a03:39a0:1f:1::daf/128 Scope:Global
          inet6 addr: fe80::ba27:ebff:fe13:a81a/64 Scope:Link
          inet6 addr: 2a03:39a0:1f:1:ba27:ebff:fe13:a81a/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4396 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4157 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:504070 (492.2 KiB)  TX bytes:1613870 (1.5 MiB)
 
sl0       Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:10.99.99.1  P-t-P:10.99.99.1  Mask:255.255.255.0
          inet6 addr: fd00:db80::1/64 Scope:Global
          inet6 addr: fe80::2b93:337e:bb:495a/64 Scope:Link
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:55 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:10
          RX bytes:0 (0.0 B)  TX bytes:8040 (7.8 KiB)
 
The wan port on my Pi3 is connected to a Linksys 1200AC running OpenWRT.  I’m wondering if I don’t have the Linksys 1200AC setup correctly to support dhcp-pd (prefix delegation) so maybe the mbed-access-point isn’t getting a prefix to use which is causing the problem???

**Comment by urutva** [comment]
@jzehler It seems like the Linksys configuration is good as the Ethernet interface is getting global IPv6 address. With the new release Neighbor Discovery Proxy(NDP) support is added, so it is not mandatory for the backahul network to support DHCP-PD. But, it seems like NDP is not enabled in your setup. Can you post the contents of `/etc/config/dhcp`?

Also, looking at the packet statistics for SLIP interface (RX packets:0) which means that the Rourter Solicitations from the HAT is not reaching the SLIP interface. It could be because the UART port available on the GPIO header is used for Bluetooth instead of SLIP interface on Raspberry Pi 3. Can you try to add `dtoverlay=pi3-disable-bt` to `/boot/config.txt`.

**Comment by jzehler** [comment]
I didn't modify /etc/config/dhcp so it should be set to the defaults in the image i built.  Contents below...

root@OpenWrt:~# cat /etc/config/dhcp

config dnsmasq
        option domainneeded '1'
        option boguspriv '1'
        option filterwin2k '0'
        option localise_queries '1'
        option rebind_protection '1'
        option rebind_localhost '1'
        option local '/lan/'
        option domain 'lan'
        option expandhosts '1'
        option nonegcache '0'
        option authoritative '1'
        option readethers '1'
        option leasefile '/tmp/dhcp.leases'
        option resolvfile '/tmp/resolv.conf.auto'
        option localservice '1'

config dhcp 'lan'
        option interface 'lan'
        option start '100'
        option limit '150'
        option leasetime '12h'
        option dhcpv6 'relay'
        option ra 'relay'
        option ndp 'hybrid'

config dhcp 'wan'
        option interface 'wan'
        option ignore '1'

config dhcp 'wan6'
        option master '1'
        option ra 'relay'
        option ndp 'relay'

config odhcpd 'odhcpd'
        option maindhcp '0'
        option leasefile '/tmp/hosts/odhcpd'
        option leasetrigger '/usr/sbin/odhcpd-update'

**Comment by jzehler** [comment]
My colleague figured out a couple things.  He found using `dtoverlay=pi3-miniuart-bt` fixed the bt uart issue on Pi3.  I confirmed your suggestion to use `dtoverlay=pi3-disable-bt` also worked on Pi3.

Note however, my colleague also found a timing issue on bootup.  Once the Pi3 completes booting, we have to ssh in and manually run `/etc/init.d/odhcpd restart`.  After doing this, I appear to now get global ipv6 addresses as shown below.  Is there a proper way to fix this bootup timing issue when the Pi3 boots so we don't have to always manually ssh in and restart odhcpd?

=====================================

root@OpenWrt:~# ifconfig
eth0      Link encap:Ethernet  HWaddr B8:27:EB:13:A8:1A
          inet addr:192.168.1.122  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: 2a03:39a0:1f:1::daf/128 Scope:Global
          inet6 addr: fe80::ba27:ebff:fe13:a81a/64 Scope:Link
          inet6 addr: 2a03:39a0:1f:1:ba27:ebff:fe13:a81a/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:507 errors:0 dropped:0 overruns:0 frame:0
          TX packets:324 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:71791 (70.1 KiB)  TX bytes:78219 (76.3 KiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:33 errors:0 dropped:0 overruns:0 frame:0
          TX packets:33 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:2660 (2.5 KiB)  TX bytes:2660 (2.5 KiB)

sl0       Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:10.99.99.1  P-t-P:10.99.99.1  Mask:255.255.255.0
          inet6 addr: 2a03:39a0:1f:1::daf/128 Scope:Global
          inet6 addr: fe80::eec:6b61:3370:2e1a/64 Scope:Link
          inet6 addr: 2a03:39a0:1f:1:ba27:ebff:fe13:a81a/64 Scope:Global
          inet6 addr: fd00:db80::1/64 Scope:Global
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:32 errors:0 dropped:0 overruns:0 frame:0
          TX packets:78 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:10
          RX bytes:2654 (2.5 KiB)  TX bytes:13198 (12.8 KiB)

=====================================

[INFO][brro]: Backhaul interface addresses:
[INFO][brro]:  [0] fe80::3441:efff:fe1f:b139
[INFO][brro]:  [1] 2a03:39a0:1f:1:21b4:1faa:6cb9:ed1a
[INFO][brro]: RF interface addresses:
[INFO][brro]:  [0] fe80::7ca8:4689:2c84:8f3e
[INFO][brro]:  [1] fd00:db8::d140:b374:5f4b:ee84
[INFO][brro]:  [2] fd00:db8::ff:fe00:8000
[INFO][brro]:  [3] fd00:db8::ff:fe00:fc00
[INFO][brro]:  [4] fd00:db8::ff:fe00:fc01
[INFO][brro]:  [5] 2a03:39a0:1f:1:7ca8:4689:2c84:8f3e

**Comment by urutva** [comment]
@jzehler 
For RPI3 device tree overlay is required to force either to disable BT or move it miniuart. About restarting the odhcpd, it’s already done in “/etc/rc.local”. But, the issue was “/dev/mem“ which is disabled by default in OpenWrt kernel config. Because of this the line https://github.com/ARMmbed/mbed-access-point/blob/a7dd62481005a924d9905dc57e0c210396bd5102/package/base-files/files/etc/rc.local#L39 fails leading to not restarting the odhcpd module. Can you try the following steps and rebuild the image for RPI3?

`make kernel_menuconfig CONFIG_TARGET=subtarget`
Search for “devmem” and select “/dev/mem virtual device support“
`make target/linux/clean`
`make`
This will fix the odhcpd issue you are having.

**Comment by jzehler** [comment]
Devaraj,

That fixed the odhcpd restart issue!  With the dtoverlay fix and this odhcpd fix, my Pi3 now boots up correctly and I get global ipv6 addresses correctly assigned.

Thanks!
-Jeff
