### ISSUE TITLE
Unable to log into ARM-BR using Thread 1.1 Commissioning App

### ISSUE THREAD

**Issue by jzehler** [ARMmbed/mbed-access-point#6]
I'm following the instructions in the README.md to perform Thead commissioning application test...
https://github.com/ARMmbed/mbed-access-point#thread-commissioning-application-test

The Thread 1.1 Commissioning App discovers ARM-BR and the ipv6 it shows matches the ipv6 of the backhaul interface on the HAT.  When I select ARM-BR, it shows a popup for Thread Admin Password.  When I enter `Thread Network` as the default password, it tells me password is incorrect.

**Comment by jzehler** [comment]
Here is the application debug log from Thread 1.1 Commissioning App...

--------- beginning of main
[ 08-08 18:22:21.225  2292: 3091 D/MeshCop  ]
Keep Alive thread: wait...

[ 08-08 18:22:26.217  2292: 2309 D/OIC_CA_CONN_MGR ]
Selected network : 1

[ 08-08 18:22:26.217  2292: 2309 D/OIC_CA_NW_CONFIG ]
Create network list

[ 08-08 18:22:26.217  2292: 2309 D/OIC_CA_NW_CONFIG ]
Add network type(IP)

[ 08-08 18:22:26.217  2292: 2309 D/OIC_CA_INF_CTR ]
Start the adapter of CAConnectivityType[1]

[ 08-08 18:22:26.217  2292: 2309 D/OIC_CA_IP_MONITOR ]
CAIPJniInit_IN

[ 08-08 18:22:26.219  2292: 2309 D/OIC_CA_IP_MONITOR ]
Create CaIpInterface instance, success

[ 08-08 18:22:26.219  2292: 2309 D/OIC_CA_IP_MONITOR ]
CAIPJniInit_OUT

[ 08-08 18:22:26.219  2292: 2309 D/OIC_CA_QING ]
thread initialize..

[ 08-08 18:22:26.220  2292: 2309 D/UTHREADPOOL ]
IN

[ 08-08 18:22:26.220  2292: 2309 D/UTHREADPOOL ]
OUT

[ 08-08 18:22:26.220  2292: 3112 D/OIC_CA_QING ]
message handler main thread start..

[ 08-08 18:22:26.220  2292: 3112 D/OIC_CA_QING ]
wait..

[ 08-08 18:22:26.221  2292: 2309 I/OIC_CA_IP_SERVER ]
IPv6 unicast port: 33366

[ 08-08 18:22:26.223  2292: 2309 I/OIC_CA_IP_SERVER ]
IPv4 unicast port: 57836

[ 08-08 18:22:26.223  2292: 2309 D/OIC_CA_IP_SERVER ]
socket summary: u6=42, u6s=71, u4=96, u4s=99, m6=84, m6s=94, m4=102, m4s=103

[ 08-08 18:22:26.223  2292: 2309 D/OIC_CA_IP_SERVER ]
port summary: u6 port=33366, u6s port=37241, u4 port=57836, u4s port=46706, m6 port=5683,m6s port=5684, m4 port=5683, m4s port=5684

[ 08-08 18:22:26.224  2292: 2309 D/OIC_CA_IP_SERVER ]
IP network interfaces found: 2

[ 08-08 18:22:26.224  2292: 2309 D/OIC_CA_IP_SERVER ]
IPv4 network interface: wlan0

[ 08-08 18:22:26.224  2292: 2309 D/OIC_CA_IP_SERVER ]
IPv6 network interface: wlan0

[ 08-08 18:22:26.224  2292: 2309 D/UTHREADPOOL ]
IN

[ 08-08 18:22:26.224  2292: 2309 D/UTHREADPOOL ]
OUT

[ 08-08 18:22:26.224  2292: 2309 D/OIC_CA_IP_SERVER ]
CAReceiveHandler thread started successfully.

[ 08-08 18:22:26.224  2292: 2309 D/OIC_CA_CONN_MGR ]
CAAddNetworkType(CA_IP_ADAPTER) function returns result: 0

[ 08-08 18:22:26.227  2292: 2309 D/OIC_CA_CONN_MGR ]
CAGenerateToken

[ 08-08 18:22:26.227  2292: 2309 D/OIC_CA_PRTCL_MSG ]
token len:8, token:

[ 08-08 18:22:26.227  2292: 2309 D/OIC_CA_PRTCL_MSG ]
AB 7C 8A 86 23 A1 68 35

[ 08-08 18:22:26.227  2292: 2309 D/OIC_CA_CONN_MGR ]
CASendRequest

[ 08-08 18:22:26.227  2292: 2309 D/OIC_CA_MSG_HANDLE ]
CAPrepareSendData IN

[ 08-08 18:22:26.227  2292: 2309 D/OIC_CA_BWT ]
There is no block data

[ 08-08 18:22:26.227  2292: 2309 D/OIC_CA_BWT ]
payloadLen=17, maxBlockSize=1024

[ 08-08 18:22:26.227  2292: 2309 D/OIC_CA_BWT ]
IN-CACreateNewBlockData

[ 08-08 18:22:26.227  2292: 2309 D/OIC_CA_BWT ]
BlockID is

[ 08-08 18:22:26.227  2292: 2309 D/OIC_CA_BWT ]
AB 7C 8A 86 23 A1 68 35 C0 27

[ 08-08 18:22:26.227  2292: 2309 D/OIC_CA_BWT ]
OUT-CreateBlockData

[ 08-08 18:22:26.227  2292: 2309 D/OIC_CA_MSG_HANDLE ]
normal msg will be sent

[ 08-08 18:22:26.227  2292: 2309 D/UQUEUE   ]
Queue Count : 1

[ 08-08 18:22:26.227  2292: 2309 I/CommPet  ]
Request sent successfully

[ 08-08 18:22:26.227  2292: 2309 D/OIC_CA_CONN_MGR ]
CADestroyEndpoint

[ 08-08 18:22:26.227  2292: 3088 D/OIC_CA_QING ]
wake up..

[ 08-08 18:22:26.227  2292: 3088 D/OIC_CA_MSG_HANDLE ]
Unicast message

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_MSG_HANDLE ]
requestInfo is available..

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_PRTCL_MSG ]
url : coap://[::]//c/cp

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_PRTCL_MSG ]
parse Head Opt: 2

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_PRTCL_MSG ]
Head opt ID: 12

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_PRTCL_MSG ]
Head opt data: *

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_PRTCL_MSG ]
Head opt length: 1

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_PRTCL_MSG ]
Head opt ID: 17

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_PRTCL_MSG ]
Head opt data: *

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_PRTCL_MSG ]
Head opt length: 1

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_PRTCL_MSG ]
transport type: 0, payload size: 17

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_PRTCL_MSG ]
msgID is 0

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_PRTCL_MSG ]
gen msg id=55794

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_PRTCL_MSG ]
messageId in pdu is 55794, 55794

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_PRTCL_MSG ]
token info token length: 8, token :

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_PRTCL_MSG ]
AB 7C 8A 86 23 A1 68 35

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_BWT ]
IN-AddBlockOption

[ 08-08 18:22:26.228  2292: 3088 D/OIC_CA_BWT ]
dataLength - 17

[ 08-08 18:22:26.230  2292: 3088 D/OIC_CA_BWT ]
BlockID is

[ 08-08 18:22:26.230  2292: 3088 D/OIC_CA_BWT ]
AB 7C 8A 86 23 A1 68 35 C0 27

[ 08-08 18:22:26.230  2292: 3088 D/OIC_CA_BWT ]
IN-GetBlockOptionType

[ 08-08 18:22:26.230  2292: 3088 D/OIC_CA_BWT ]
OUT-GetBlockOptionType

[ 08-08 18:22:26.230  2292: 3088 D/OIC_CA_BWT ]
no BLOCK option

[ 08-08 18:22:26.230  2292: 3088 D/OIC_CA_BWT ]
[c] opt will be added.

[ 08-08 18:22:26.230  2292: 3088 D/OIC_CA_BWT ]
[12] pdu length

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_BWT ]
[cp] opt will be added.

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_BWT ]
[14] pdu length

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_BWT ]
[*] opt will be added.

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_BWT ]
[17] pdu length

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_BWT ]
[*] opt will be added.

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_BWT ]
[19] pdu length

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_BWT ]
[21] pdu length after option

[ 08-08 18:22:26.231  2292: 3088 I/OIC_CA_BWT ]
not Blockwise Transfer

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_BWT ]
OUT-AddBlockOption

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_MSG_HANDLE ]
PDU Maker - payload : 
AndroidComm5104

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_MSG_HANDLE ]
PDU Maker - type : 0

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_MSG_HANDLE ]
PDU Maker - code : 2

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_MSG_HANDLE ]
PDU Maker - token :

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_MSG_HANDLE ]
AB 7C 8A 86 23 A1 68 35

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_INF_CTR ]
unicast message to adapter

[ 08-08 18:22:26.231  2292: 3088 D/UQUEUE   ]
Queue Count : 1

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_RETRANS ]
sent pdu, msgtype=0, msgid=55794

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_RETRANS ]
IN

[ 08-08 18:22:26.231  2292: 3088 D/OIC_CA_RETRANS ]
current time = 150794211415

[ 08-08 18:22:26.232  2292: 3088 D/OIC_CA_RETRANS ]
OUT

[ 08-08 18:22:26.232  2292: 3112 D/OIC_CA_QING ]
wake up..

[ 08-08 18:22:26.232  2292: 3088 D/OIC_CA_MSG_HANDLE ]
CADestroyData IN

[ 08-08 18:22:26.232  2292: 3088 D/OIC_CA_MSG_HANDLE ]
CADestroyData OUT

[ 08-08 18:22:26.232  2292: 3088 D/OIC_CA_QING ]
wait..

[ 08-08 18:22:26.232  2292: 3112 D/OIC_CA_IP_ADAP ]
CAAdapterNetDtlsEncrypt called!

[ 08-08 18:22:26.232  2292: 3112 D/OIC_CA_NET_DTLS ]
IN

[ 08-08 18:22:26.232  2292: 3112 D/OIC_CA_NET_DTLS ]
Data to be encrypted dataLen [39]

[ 08-08 18:22:26.232  2292: 3112 D/OIC_CA_NET_DTLS ]
IN

[ 08-08 18:22:26.233  2292: 3112 D/OIC_CA_NET_DTLS ]
IN

[ 08-08 18:22:26.234  2292: 3090 D/OIC_CA_RETRANS ]
wake up..

[ 08-08 18:22:26.234  2292: 3090 D/OIC_CA_RETRANS ]
IN

[ 08-08 18:22:26.234  2292: 3090 D/OIC_CA_RETRANS ]
current time = 150794213593

[ 08-08 18:22:26.234  2292: 3090 D/OIC_CA_RETRANS ]
OUT

[ 08-08 18:22:26.234  2292: 3090 D/OIC_CA_RETRANS ]
wait..(1000000)microseconds

[ 08-08 18:22:26.242  2292: 2292 D/OIC_CA_IP_MONITOR ]
Wifi is in Activated State

[ 08-08 18:22:26.242  2292: 2292 D/OIC_CA_INF_CTR ]
[1]adapter status is changed to [1]

[ 08-08 18:22:26.245  2292: 3112 D/OIC_CA_NET_DTLS ]
IN

[ 08-08 18:22:26.247  2292: 3112 D/OIC_CA_IP_SERVER ]
IN

[ 08-08 18:22:26.247  2292: 3112 I/OIC_CA_IP_SERVER ]
secure unicast ipv6 sendTo is successful: 421 bytes

[ 08-08 18:22:26.248  2292: 3112 D/OIC_CA_NET_DTLS ]
OUT

[ 08-08 18:22:26.248  2292: 3112 D/OIC_CA_NET_DTLS ]
IN

[ 08-08 18:22:26.248  2292: 3112 D/OIC_CA_NET_DTLS ]
level [0] code [476]
[ 08-08 18:22:26.248  2292: 3112 D/OIC_CA_NET_DTLS ]
OUT

[ 08-08 18:22:26.248  2292: 3112 D/OIC_CA_NET_DTLS ]
dtls_write retun len [0]

[ 08-08 18:22:26.248  2292: 3112 D/OIC_CA_NET_DTLS ]
IN

[ 08-08 18:22:26.248  2292: 3112 D/OIC_CA_NET_DTLS ]
OUT

[ 08-08 18:22:26.248  2292: 3112 D/OIC_CA_NET_DTLS ]
OUT Initiating Dtls session [0]

[ 08-08 18:22:26.248  2292: 3112 D/OIC_CA_IP_ADAP ]
DTLS retransmission not necessary

[ 08-08 18:22:26.248  2292: 3112 D/OIC_CA_IP_ADAP ]
CAAdapterNetDtlsEncrypt returned with result[0]

[ 08-08 18:22:26.248  2292: 3112 D/OIC_CA_QING ]
wait..

[ 08-08 18:22:27.272  2292: 3090 D/OIC_CA_RETRANS ]
IN

[ 08-08 18:22:27.273  2292: 3090 D/OIC_CA_RETRANS ]
current time = 150795252415

[ 08-08 18:22:27.273  2292: 3090 D/OIC_CA_RETRANS ]
OUT

[ 08-08 18:22:27.273  2292: 3090 D/OIC_CA_RETRANS ]
wait..(1000000)microseconds

[ 08-08 18:22:28.312  2292: 3090 D/OIC_CA_RETRANS ]
IN

[ 08-08 18:22:28.312  2292: 3090 D/OIC_CA_RETRANS ]
current time = 150796291749

[ 08-08 18:22:28.312  2292: 3090 D/OIC_CA_RETRANS ]
OUT

[ 08-08 18:22:28.312  2292: 3090 D/OIC_CA_RETRANS ]
wait..(1000000)microseconds

**Comment by urutva** [comment]
@jzehler Thanks for reporting! We are looking into this. We'll update when we have more information.

**Comment by jzehler** [comment]
@devran01 What does "thread-use-static-link-config" do in Thread_SLIP_Atmel_RF.json?  It's set to true by default.  I see what appears to be Thread preset network settings in the json file like "thread-master-key", "pan-id", "extended-pan-id", etc.  Do I need to change a setting to tell the Thread stack to let Thread 1.1 Commissioning App setup the Thread network?

**Comment by urutva** [comment]
The parameter `thread-use-static-link-config` is described in https://github.com/ARMmbed/mbed-os/tree/master/features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api. For the thread border router, if this flag is unset then without commissioning, thread end nodes cannot join the network that BR is advertising. This parameter should not affect the thread commissioning process. 

Can you please provide the tcpdump log of the ethernet interface on the backbone access point and the ethernet interface on the mbed access point?

**Comment by urutva** [comment]
@jzehler Are you still facing the issue with thread commissioning app?

**Comment by jzehler** [comment]
@devran01 I applied the ipk you provided my colleagues for the odhcpd routing issue fix for Pi3.  I also had to change my ULA prefix length from /60 to /48 on my Linksys WRT1200AC running OpenWRT.  Once I did those steps, I can now connect to the ARM-BR using Thread 1.1 Commissioning App.  Thanks!
